
-- 1. 판매량
CREATE TABLE SULIM_SALE_CNT_BY_PRDG AS
SELECT /*+ PARALLEL(8) FULL(A) */
       SALE_YYMM, PRDG_CD, COUNT(1) CNT
  FROM WJM.TW_CT_SALE_MST_MM A
 WHERE 1=1
--   AND SALE_YYMM = '201907'
   AND PORD_YN = 'X'
   AND TOVR_SALE_YN <> 'X'
   AND PRDG_CD = '001'
 GROUP BY SALE_YYMM, PRDG_CD
;

CREATE TABLE SULIM_SALT_CNT_BY_PRDG AS
SELECT /*+ PARALLEL(8) FULL(A) */
       SALE_YYMM, PRDG_CD,COUNT(1) CNT
  FROM WJM.TW_CT_SALE_MST_MM A
 WHERE 1=1
--   AND SALE_YYMM = '201907'
   AND TORD_YN = 'X'
   AND TOVR_SALE_YN <> 'X'
   AND PRDG_CD = '001'
 GROUP BY SALE_YYMM, PRDG_CD
;

-- 2. 해약건수
CREATE TABLE SULIM_CNCL_CNT_BY_PRDG AS
SELECT /*+ PARALLEL(8) FULL(A) */
       A.PROD_YM, B.PRDG_CD, COUNT(1) CNT
  FROM WJO.TO_ZBWT1003 A
      ,WJM.TD_PD_PROD B
 WHERE A.PROD_DAY = TO_CHAR(ADD_MONTHS(TO_DATE(A.PROD_YM,'YYYYMM'),1)-1,'DD')
   AND A.RTN_CONF_DT BETWEEN '19900101' AND '99991231'
   AND A.CONTRACT_ID   = '2'
   AND A.VALUATION_CK1 = 'X'
   AND A.GOODS_CD = B.PROD_CD
 GROUP BY A.PROD_YM, B.PRDG_CD
 ORDER BY A.PROD_YM
;

-- 3. 소유권도래건수
CREATE TABLE SULIM_OWNE_CNT_BY_PRDG AS
SELECT /*+ PARALLEL(8) FULL(A B) */ 
       A.YYYY_MM, B.PRDG_CD
      ,COUNT(1) CNT 
  FROM TO_ZSDT1048 A
      ,WJM.TD_PD_PROD B 
 WHERE A.YYYY_MM = A.FIRST_YM
   AND A.GOODS_CD = B.PROD_CD
 GROUP BY A.YYYY_MM, B.PRDG_CD
;


-- 4. 영업조직원수
--CREATE TABLE SULIM_ORGM_CNT AS
SELECT /*+ PARALLEL(8) FULL(A) */
       SALE_YYMM, COUNT(DISTINCT SALE_EMP_NO) EMP_CNT, COUNT(DISTINCT SALE_ORG_CD) ORG_CNT
  FROM WJM.TW_CT_SALE_MST_MM A
 GROUP BY SALE_YYMM;
 
 
-- 101. 전전월대비 전월 순주문 증가율
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-2),'YYYYMM') AS M_2
      ,PORD_CNT
  FROM VW_TMP
)
SELECT ROUND((B1.PORD_CNT-B2.PORD_CNT)/B2.PORD_CNT,5) AS PORD_INCR_PCNT
      ,A.PORD_CNT
      ,A.SALE_YYMM
  FROM VW_TMP2 A
      ,VW_TMP B1
      ,VW_TMP B2
 WHERE 1=1
   AND A.M_1 = B1.SALE_YYMM
   AND A.M_2 = B2.SALE_YYMM
;

-- 2. 최근3개월 평균 순주문 증가율
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-2),'YYYYMM') AS M_2
      ,PORD_CNT
  FROM VW_TMP
)
,VW_TMP3 AS (
SELECT ROUND((B1.PORD_CNT-B2.PORD_CNT)/B2.PORD_CNT,5) AS PORD_INCR_PCNT
      ,A.PORD_CNT
      ,A.SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') AS M_2
  FROM VW_TMP2 A
      ,VW_TMP B1
      ,VW_TMP B2
 WHERE 1=1
   AND A.M_1 = B1.SALE_YYMM
   AND A.M_2 = B2.SALE_YYMM
)
SELECT 
       A.SALE_YYMM
      ,ROUND((A.PORD_INCR_PCNT+B1.PORD_INCR_PCNT+B2.PORD_INCR_PCNT)/3,5) AS AVG_PORD_INCR_PCNT
      ,A.PORD_CNT
  FROM VW_TMP3 A
      ,VW_TMP3 B1
      ,VW_TMP3 B2
 WHERE A.M_1 = B1.SALE_YYMM
   AND A.M_2 = B2.SALE_YYMM;
   
-- 3. 전월 전년 동월 대비 증가율
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
      ,TO_CHAR(ADD_MONTHS(TO_DATE(SALE_YYMM,'YYYYMM'),-13),'YYYYMM') AS M_13
      ,PORD_CNT
  FROM VW_TMP
)
SELECT ROUND((B1.PORD_CNT-B2.PORD_CNT)/B2.PORD_CNT,5) AS PORD_INCR_PCNT
      ,A.PORD_CNT
      ,A.SALE_YYMM
  FROM VW_TMP2 A
      ,VW_TMP B1
      ,VW_TMP B2
 WHERE A.M_1 = B1.SALE_YYMM
   AND A.M_13 = B2.SALE_YYMM
;

-- 4. 전월 인당생산성
--CREATE TABLE SULIM_INDEX_PPP AS
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT ROUND(A.PORD_CNT/B.EMP_CNT,3) AS PPP
      ,A.PORD_CNT
      ,A.SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
  FROM VW_TMP A
      ,SULIM_ORGM_CNT B
 WHERE A.SALE_YYMM = B.SALE_YYMM
)
SELECT A.SALE_YYMM
      ,B.PPP
      ,A.PORD_CNT
  FROM VW_TMP2 A
      ,VW_TMP2 B
 WHERE A.M_1 = B.SALE_YYMM
;

-- 5. 직전3개월 인당생산성
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT ROUND(A.PORD_CNT/B.EMP_CNT,3) AS PPP
      ,A.PORD_CNT
      ,A.SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') AS M_2
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-3),'YYYYMM') AS M_3
  FROM VW_TMP A
      ,SULIM_ORGM_CNT B
 WHERE A.SALE_YYMM = B.SALE_YYMM
)
SELECT ROUND((B1.PPP+B2.PPP+B3.PPP)/3,3) AS AVG_PPP
      ,A.PORD_CNT
      ,A.SALE_YYMM
  FROM VW_TMP2 A
      ,VW_TMP2 B1
      ,VW_TMP2 B2
      ,VW_TMP2 B3
 WHERE 1=1
   AND A.M_1 = B1.SALE_YYMM
   AND A.M_2 = B2.SALE_YYMM
   AND A.M_3 = B3.SALE_YYMM
;

-- 6. 전월 부서당생산성
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
,VW_TMP2 AS (
SELECT ROUND(A.PORD_CNT/B.ORG_CNT,3) AS PPD
      ,A.PORD_CNT
      ,A.SALE_YYMM
      ,TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M_1
  FROM VW_TMP A
      ,SULIM_ORGM_CNT B
 WHERE A.SALE_YYMM = B.SALE_YYMM
)
SELECT B.PPD
      ,A.PORD_CNT
      ,A.SALE_YYMM
  FROM VW_TMP2 A
      ,VW_TMP2 B
 WHERE A.M_1 = B.SALE_YYMM
;

-- 7. 해약건수
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
SELECT B.CNT AS CNCL_CNT
      ,A.PORD_CNT
      ,A.SALE_YYMM
  FROM VW_TMP A
      ,SULIM_CNCL_CNT_BY_PRDG B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.PROD_YM
   AND B.PRDG_CD = '001'
;

-- 8. 최근3개월 해약건수
--CREATE TABLE SULIM_INDEX_AVG_CNCL_CNT AS
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
SELECT 
       A.SALE_YYMM
      ,ROUND((B1.CNT+B2.CNT+B3.CNT)/3,2) AS AVG_CNCL_CNT
      ,A.PORD_CNT
  FROM VW_TMP A
      ,SULIM_CNCL_CNT_BY_PRDG B1
      ,SULIM_CNCL_CNT_BY_PRDG B2
      ,SULIM_CNCL_CNT_BY_PRDG B3
 WHERE 1=1
   AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B1.PROD_YM
   AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') = B2.PROD_YM
   AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-3),'YYYYMM') = B3.PROD_YM
   AND B1.PRDG_CD = '001'
   AND B2.PRDG_CD = '001'
   AND B3.PRDG_CD = '001'
;

-- 9. 전월 소유건도래건수
--CREATE TABLE SULIM_INDEX_OWNE_CNT AS
WITH VW_TMP AS (
SELECT SALE_YYMM, 
       PRDG_CD,
       CNT AS PORD_CNT
  FROM SULIM_SALE_CNT_BY_PRDG
 WHERE PRDG_CD = '001'
)
SELECT A.SALE_YYMM
      ,B.CNT AS OWNE_CNT
      ,A.PORD_CNT
  FROM VW_TMP A
      ,SULIM_OWNE_CNT_BY_PRDG B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.YYYY_MM
   AND B.PRDG_CD = '001'
;

-- 10. 전월 프로모션건수
WITH VW_TMP AS (
SELECT SALE_YYMM, SUM(CNT) PORD_CNT
  FROM SULIM_SALE_CNT
 GROUP BY SALE_YYMM
)
, VW_TMP2 AS (
SELECT SALE_YYMM
      ,COUNT(DISTINCT SALE_PRM_CD) PRM_CNT
  FROM SULIM_SALE_CNT
 WHERE SALE_PRM_CD <> 'Z#'
   AND LENGTH(TRIM(SALE_PRM_CD))>0
--   AND CNT > 100
 GROUP BY SALE_YYMM
)
SELECT A.SALE_YYMM
      ,SUM(A.PORD_CNT) AS PORD_CNT
      ,SUM(B.PRM_CNT)  AS PRM_CNT
  FROM VW_TMP A
      ,VW_TMP2 B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM(+)
 GROUP BY A.SALE_YYMM
;

-- 11. 전월 프로모션 판매건수
WITH VW_TMP AS (
SELECT SALE_YYMM, SUM(CNT) PORD_CNT
  FROM SULIM_SALE_CNT
 GROUP BY SALE_YYMM
)
, VW_TMP2 AS (
SELECT SALE_YYMM
      ,SUM(CNT) PRM_CNT
  FROM SULIM_SALE_CNT
 WHERE SALE_PRM_CD <> 'Z#'
   AND LENGTH(TRIM(SALE_PRM_CD))>0
--   AND CNT > 100
 GROUP BY SALE_YYMM
)
SELECT A.SALE_YYMM
      ,SUM(A.PORD_CNT) AS PORD_CNT
      ,SUM(NVL(B.PRM_CNT,0))  AS PRM_CNT
  FROM VW_TMP A
      ,VW_TMP2 B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM(+)
 GROUP BY A.SALE_YYMM
;

-- 13. 전월 요금제 등급별 비중
DROP TABLE SULIM_INDEX_HG_PCNT;
CREATE TABLE SULIM_INDEX_HG_PCNT AS
WITH VW_TMP AS (
SELECT SALE_YYMM
      ,SUM(CNT) AS TOT_CNT
  FROM SULIM_SALE_CNT
 GROUP BY SALE_YYMM
)
, VW_RTFEE_MST_TMP AS (
SELECT ROW_NUMBER() OVER (PARTITION BY SALE_YYMM ORDER BY RTFEE DESC) RN
      ,SALE_YYMM
      ,RTFEE
  FROM (SELECT SALE_YYMM
              ,RTFEE
          FROM SULIM_SALE_CNT
         WHERE RTFEE > 0 
         GROUP BY
               SALE_YYMM
              ,RTFEE ) S
)
, VW_RTFEE_MST_TMP2 AS (
SELECT SALE_YYMM, MAX(RN) MAX_RN
  FROM VW_RTFEE_MST_TMP
 GROUP BY
       SALE_YYMM
)
, VW_RTFEE_MST AS (
SELECT SALE_YYMM
      ,RTFEE
      ,CASE WHEN GRADE_DTL BETWEEN 81 AND 100 THEN '저가'
            WHEN GRADE_DTL BETWEEN 61 AND  80 THEN '중저가'
            WHEN GRADE_DTL BETWEEN 41 AND  60 THEN '중가'
            WHEN GRADE_DTL BETWEEN 21 AND  40 THEN '중고가'
            WHEN GRADE_DTL BETWEEN  1 AND  20 THEN '고가'
        END AS GRADE
  FROM (SELECT A.SALE_YYMM
              ,ROUND(A.RN/B.MAX_RN*100) AS GRADE_DTL 
              ,A.RTFEE
          FROM VW_RTFEE_MST_TMP A
              ,VW_RTFEE_MST_TMP2 B
         WHERE A.SALE_YYMM = B.SALE_YYMM )
)
, VW_TMP2 AS (
SELECT A.SALE_YYMM
      ,B.GRADE
      ,SUM(A.CNT) CNT
  FROM SULIM_SALE_CNT A
      ,VW_RTFEE_MST B
 WHERE A.SALE_YYMM = B.SALE_YYMM
   AND A.RTFEE = B.RTFEE
 GROUP BY
       A.SALE_YYMM
      ,B.GRADE
)
, VW_TMP3 AS (
SELECT A.SALE_YYMM
      ,B.GRADE
      ,ROUND(B.CNT/A.TOT_CNT,5) PCNT
  FROM VW_TMP A
      ,VW_TMP2 B
 WHERE A.SALE_YYMM = B.SALE_YYMM
   AND B.GRADE IS NOT NULL
)
SELECT A.SALE_YYMM
--      ,B.GRADE
      ,B.PCNT AS HG_PCNT
--      ,A.TOT_CNT
  FROM VW_TMP A
      ,VW_TMP3 B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM
   AND B.GRADE = '고가'
;

-- 14.전월 순주문 비중
CREATE TABLE SULIM_INDEX_PORD_PCNT AS
WITH VW_TMP AS (
SELECT SALE_YYMM
      ,SUM(CNT) AS PORD_CNT
  FROM SULIM_SALE_CNT
 GROUP BY SALE_YYMM
)
, VW_TMP2 AS (
SELECT SALE_YYMM
      ,SUM(CNT) AS TORD_CNT
  FROM SULIM_SALT_CNT
 GROUP BY SALE_YYMM
)
, VW_TMP3 AS (
SELECT A.SALE_YYMM
      ,ROUND(A.PORD_CNT/B.TORD_CNT,5) PORD_PCNT
  FROM VW_TMP A
      ,VW_TMP2 B
 WHERE A.SALE_YYMM = B.SALE_YYMM
)
SELECT A.SALE_YYMM
      ,B.PORD_PCNT
--      ,A.PORD_CNT
  FROM VW_TMP A
      ,VW_TMP3 B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM