--DROP TABLE SULIM_PRDCT_MART_001;
CREATE TABLE SULIM_PRDCT_MART_001 AS
SELECT
    A.SALE_YYMM
   ,NVL(C1.B1_PORD_CNT_001 ,0) AS IDX_C1 --"전월_제품군별_판매량"
   ,NVL(E2.PRDCT_CNT_001   ,0) AS IDX_E2 --"3개월평균_인당생산성_전월반영"
   ,NVL(F1.GR_PORD_CNT_001 ,0) AS IDX_F1 --"최근6개월성장률반영_판매량"
   ,NVL(F2.GR_PORD_CNT_001 ,0) AS IDX_F2 --"최근3개월성장률반영_판매량"
   ,NVL(I1.SESSON_001      ,0) AS IDX_I1 --"연평균_계절지수반영"
   ,A.PORD_CNT                 AS CNT    --"순주문건수"
FROM
    SULIM_ORD_CNT A,
    SULIM_PRDT_IDX_C_1 C1,
    SULIM_PRDT_IDX_E_2 E2,
    SULIM_PRDT_IDX_F_1 F1,
    SULIM_PRDT_IDX_F_2 F2,
    SULIM_PRDT_IDX_I_1 I1
WHERE 1=1
AND A.SLPART_CD = '2'
AND A.PRDG_CD = '001'

AND A.SALE_YYMM = C1.SALE_YYMM
AND A.SALE_YYMM = E2.SALE_YYMM
AND A.SALE_YYMM = F1.SALE_YYMM
AND A.SALE_YYMM = F2.SALE_YYMM
AND A.SALE_YYMM = I1.SALE_YYMM

ORDER BY 1
;

--DROP TABLE SULIM_PRDCT_MART_002;
CREATE TABLE SULIM_PRDCT_MART_002 AS
SELECT
    A.SALE_YYMM
   ,NVL(C1.B1_PORD_CNT_002 ,0) AS IDX_C1 --"전월_제품군별_판매량"
   ,NVL(F1.GR_PORD_CNT_002 ,0) AS IDX_F1 --"최근6개월성장률반영_판매량"
   ,NVL(F2.GR_PORD_CNT_002 ,0) AS IDX_F2 --"최근3개월성장률반영_판매량"
   ,NVL(I1.SESSON_002      ,0) AS IDX_I1 --"연평균_계절지수반영"
   ,A.PORD_CNT                 AS CNT    --"순주문건수"
FROM
    SULIM_ORD_CNT A,
    SULIM_PRDT_IDX_C_1 C1,
    SULIM_PRDT_IDX_F_1 F1,
    SULIM_PRDT_IDX_F_2 F2,
    SULIM_PRDT_IDX_I_1 I1
WHERE 1=1
AND A.SLPART_CD = '2'
AND A.PRDG_CD = '002'

AND A.SALE_YYMM = C1.SALE_YYMM
AND A.SALE_YYMM = F1.SALE_YYMM
AND A.SALE_YYMM = F2.SALE_YYMM
AND A.SALE_YYMM = I1.SALE_YYMM

ORDER BY 1
;

--DROP TABLE SULIM_PRDCT_MART_004;
CREATE TABLE SULIM_PRDCT_MART_004 AS
SELECT
    A.SALE_YYMM
   ,NVL(C1.B1_PORD_CNT_004 ,0) AS IDX_C1 --"전월_제품군별_판매량"
   ,NVL(F1.GR_PORD_CNT_004 ,0) AS IDX_F1 --"최근6개월성장률반영_판매량"
   ,NVL(F2.GR_PORD_CNT_004 ,0) AS IDX_F2 --"최근3개월성장률반영_판매량"
   ,NVL(I1.SESSON_004      ,0) AS IDX_I1 --"연평균_계절지수반영"
   ,A.PORD_CNT                 AS CNT    --"순주문건수"
FROM
    SULIM_ORD_CNT A,
    SULIM_PRDT_IDX_C_1 C1,
    SULIM_PRDT_IDX_F_1 F1,
    SULIM_PRDT_IDX_F_2 F2,
    SULIM_PRDT_IDX_I_1 I1
WHERE 1=1
AND A.SLPART_CD = '2'
AND A.PRDG_CD = '004'

AND A.SALE_YYMM = C1.SALE_YYMM
AND A.SALE_YYMM = F1.SALE_YYMM
AND A.SALE_YYMM = F2.SALE_YYMM
AND A.SALE_YYMM = I1.SALE_YYMM

ORDER BY 1
;

--DROP TABLE SULIM_PRDCT_MART_008;
CREATE TABLE SULIM_PRDCT_MART_008 AS
SELECT
    A.SALE_YYMM
   ,NVL(A1.CNCL_CNT_008    ,0) AS IDX_A1 --"전월_해약건수" 
   ,NVL(C1.B1_PORD_CNT_008 ,0) AS IDX_C1 --"전월_제품군별_판매량"
   ,NVL(E2.PRDCT_CNT_008   ,0) AS IDX_E2 --"3개월평균_인당생산성_전월반영"
   ,NVL(I1.SESSON_008      ,0) AS IDX_I1 --"연평균_계절지수반영"
   ,A.PORD_CNT                 AS CNT    --"순주문건수"
FROM
    SULIM_ORD_CNT A,
    SULIM_PRDT_IDX_A_1 A1,
    SULIM_PRDT_IDX_C_1 C1,
    SULIM_PRDT_IDX_E_2 E2,
    SULIM_PRDT_IDX_I_1 I1
WHERE 1=1
AND A.SLPART_CD = '2'
AND A.PRDG_CD = '008'
AND A.SALE_YYMM > '201209'

AND A.SALE_YYMM = A1.SALE_YYMM
AND A.SALE_YYMM = C1.SALE_YYMM
AND A.SALE_YYMM = E2.SALE_YYMM
AND A.SALE_YYMM = I1.SALE_YYMM

ORDER BY 1
;

--DROP TABLE SULIM_PRDCT_MART_003;
CREATE TABLE SULIM_PRDCT_MART_003 AS
SELECT
    A.SALE_YYMM
   ,NVL(A1.CNCL_CNT_003    ,0) AS IDX_A1 --"전월_해약건수" 
   ,NVL(F1.GR_PORD_CNT_003 ,0) AS IDX_F1 --"최근6개월성장률반영_판매량"
   ,NVL(F2.GR_PORD_CNT_003 ,0) AS IDX_F2 --"최근3개월성장률반영_판매량"
   ,NVL(I1.SESSON_003      ,0) AS IDX_I1 --"연평균_계절지수반영"
   ,A.PORD_CNT                 AS CNT    --"순주문건수"
FROM
    SULIM_ORD_CNT A,
    SULIM_PRDT_IDX_A_1 A1,
    SULIM_PRDT_IDX_F_1 F1,
    SULIM_PRDT_IDX_F_2 F2,
    SULIM_PRDT_IDX_I_1 I1
WHERE 1=1
AND A.SLPART_CD = '2'
AND A.PRDG_CD = '003'

AND A.SALE_YYMM = A1.SALE_YYMM
AND A.SALE_YYMM = F1.SALE_YYMM
AND A.SALE_YYMM = F2.SALE_YYMM
AND A.SALE_YYMM = I1.SALE_YYMM
AND A1.CNCL_CNT_003>10
AND F1.GR_PORD_CNT_003>10
AND F2.GR_PORD_CNT_003>10
AND I1.SESSON_003>10
AND A.PORD_CNT>10

ORDER BY 1
;

--DROP TABLE SULIM_PRDCT_MART_TP1;
CREATE TABLE SULIM_PRDCT_MART_TP1 AS
SELECT
    H1.SALE_YYMM,
    H1.PORD_CNT_M1  AS IDX_H1,
    H2.PORD_CNT_M3  AS IDX_H2,
    E3.PRDCT_CNT    AS IDX_E3,
    H1.PORD_CNT
    
FROM
    SULIM_PRDT_IDX_H_1 H1,
    SULIM_PRDT_IDX_E_3 E3,
    SULIM_PRDT_IDX_H_2 H2
WHERE 1=1
AND H1.SALE_YYMM = E3.SALE_YYMM
AND H1.SALE_YYMM = H2.SALE_YYMM

ORDER BY
    SALE_YYMM;

SELECT * FROM SULIM_PRDCT_MART_001 ORDER BY 1 DESC;
SELECT * FROM SULIM_PRDCT_MART_002 ORDER BY 1 DESC;
SELECT * FROM SULIM_PRDCT_MART_004 ORDER BY 1 DESC;
SELECT * FROM SULIM_PRDCT_MART_008 ORDER BY 1 DESC;
SELECT * FROM SULIM_PRDCT_MART_003 ORDER BY 1 DESC;
SELECT * FROM SULIM_PRDCT_MART_TP1 ORDER BY 1 DESC;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_C1) AS MAX_IDX_C1,
    MIN(IDX_C1) AS MIN_IDX_C1,
    MAX(IDX_E2) AS MAX_IDX_E2,
    MIN(IDX_E2) AS MIN_IDX_E2,
    MAX(IDX_F1) AS MAX_IDX_F1,
    MIN(IDX_F1) AS MIN_IDX_F1,
    MAX(IDX_F2) AS MAX_IDX_F2,
    MIN(IDX_F2) AS MIN_IDX_F2,
    MAX(IDX_I1) AS MAX_IDX_I1,
    MIN(IDX_I1) AS MIN_IDX_I1,
    MAX(CNT)    AS MAX_CNT,
    MIN(CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_001
)
SELECT
    SALE_YYMM,
    ROUND((IDX_C1-MIN_IDX_C1)/(MAX_IDX_C1-MIN_IDX_C1)*100,5) AS NORM_IDX_C1,
    ROUND((IDX_E2-MIN_IDX_E2)/(MAX_IDX_E2-MIN_IDX_E2)*100,5) AS NORM_IDX_E2,
    ROUND((IDX_F1-MIN_IDX_F1)/(MAX_IDX_F1-MIN_IDX_F1)*100,5) AS NORM_IDX_F1,
    ROUND((IDX_F2-MIN_IDX_F2)/(MAX_IDX_F2-MIN_IDX_F2)*100,5) AS NORM_IDX_F2,
    ROUND((IDX_I1-MIN_IDX_I1)/(MAX_IDX_I1-MIN_IDX_I1)*100,5) AS NORM_IDX_I1,
    ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT,
    cnt,MIN_CNT,MAX_CNT,
    ROUND(ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5)/100*(MAX_CNT-MIN_CNT)+MIN_CNT) LOGIC
FROM
    SULIM_PRDCT_MART_001 A,
    VW_MIN_MAX B
WHERE 1=1
order by 1 desc
;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_A1) AS MAX_IDX_A1,
    MIN(IDX_A1) AS MIN_IDX_A1,
    MAX(IDX_C1) AS MAX_IDX_C1,
    MIN(IDX_C1) AS MIN_IDX_C1,
    MAX(IDX_E2) AS MAX_IDX_E2,
    MIN(IDX_E2) AS MIN_IDX_E2,
    MAX(IDX_I1) AS MAX_IDX_I1,
    MIN(IDX_I1) AS MIN_IDX_I1,
    MAX(CNT)    AS MAX_CNT,
    MIN(CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_008
)
SELECT
    SALE_YYMM,
    CNT,
    ROUND((IDX_A1-MIN_IDX_A1)/(MAX_IDX_A1-MIN_IDX_A1)*100,5) AS NORM_IDX_A1,
    ROUND((IDX_C1-MIN_IDX_C1)/(MAX_IDX_C1-MIN_IDX_C1)*100,5) AS NORM_IDX_C1,
    ROUND((IDX_E2-MIN_IDX_E2)/(MAX_IDX_E2-MIN_IDX_E2)*100,5) AS NORM_IDX_E2,
    ROUND((IDX_I1-MIN_IDX_I1)/(MAX_IDX_I1-MIN_IDX_I1)*100,5) AS NORM_IDX_I1,
    ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT
FROM
    SULIM_PRDCT_MART_008 A,
    VW_MIN_MAX B
WHERE 1=1
;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_C1) AS MAX_IDX_C1,
    MIN(IDX_C1) AS MIN_IDX_C1,
    MAX(IDX_F1) AS MAX_IDX_F1,
    MIN(IDX_F1) AS MIN_IDX_F1,
    MAX(IDX_F2) AS MAX_IDX_F2,
    MIN(IDX_F2) AS MIN_IDX_F2,
    MAX(IDX_I1) AS MAX_IDX_I1,
    MIN(IDX_I1) AS MIN_IDX_I1,
    MAX(CNT)    AS MAX_CNT,
    MIN(CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_004
)
SELECT
    SALE_YYMM,
    CNT,
    ROUND((IDX_C1-MIN_IDX_C1)/(MAX_IDX_C1-MIN_IDX_C1)*100,5) AS NORM_IDX_C1,
    ROUND((IDX_F1-MIN_IDX_F1)/(MAX_IDX_F1-MIN_IDX_F1)*100,5) AS NORM_IDX_F1,
    ROUND((IDX_F2-MIN_IDX_F2)/(MAX_IDX_F2-MIN_IDX_F2)*100,5) AS NORM_IDX_F2,
    ROUND((IDX_I1-MIN_IDX_I1)/(MAX_IDX_I1-MIN_IDX_I1)*100,5) AS NORM_IDX_I1,
    ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT
FROM
    SULIM_PRDCT_MART_004 A,
    VW_MIN_MAX B
WHERE 1=1
AND SALE_YYMM <> '201907'
;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_A1) AS MAX_IDX_A1,
    MIN(IDX_A1) AS MIN_IDX_A1,
    MAX(IDX_C1) AS MAX_IDX_C1,
    MIN(IDX_C1) AS MIN_IDX_C1,
    MAX(IDX_E2) AS MAX_IDX_E2,
    MIN(IDX_E2) AS MIN_IDX_E2,
    MAX(IDX_I1) AS MAX_IDX_I1,
    MIN(IDX_I1) AS MIN_IDX_I1,
    MAX(CNT)    AS MAX_CNT,
    MIN(CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_008
)
SELECT
    SALE_YYMM,
    CNT,
    ROUND((IDX_A1-MIN_IDX_A1)/(MAX_IDX_A1-MIN_IDX_A1)*100,5) AS NORM_IDX_A1,
    ROUND((IDX_C1-MIN_IDX_C1)/(MAX_IDX_C1-MIN_IDX_C1)*100,5) AS NORM_IDX_C1,
    ROUND((IDX_E2-MIN_IDX_E2)/(MAX_IDX_E2-MIN_IDX_E2)*100,5) AS NORM_IDX_E2,
    ROUND((IDX_I1-MIN_IDX_I1)/(MAX_IDX_I1-MIN_IDX_I1)*100,5) AS NORM_IDX_I1,
    ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT
FROM
    SULIM_PRDCT_MART_008 A,
    VW_MIN_MAX B
WHERE 1=1
AND SALE_YYMM <> '201907'
;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_A1) AS MAX_IDX_A1,
    MIN(IDX_A1) AS MIN_IDX_A1,
    MAX(IDX_F1) AS MAX_IDX_F1,
    MIN(IDX_F1) AS MIN_IDX_F1,
    MAX(IDX_F2) AS MAX_IDX_F2,
    MIN(IDX_F2) AS MIN_IDX_F2,
    MAX(IDX_I1) AS MAX_IDX_I1,
    MIN(IDX_I1) AS MIN_IDX_I1,
    MAX(CNT)    AS MAX_CNT,
    MIN(CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_003
)
SELECT
    SALE_YYMM,
    CNT,
    ROUND((IDX_A1-MIN_IDX_A1)/(MAX_IDX_A1-MIN_IDX_A1)*100,5) AS NORM_IDX_A1,
    ROUND((IDX_F1-MIN_IDX_F1)/(MAX_IDX_F1-MIN_IDX_F1)*100,5) AS NORM_IDX_F1,
    ROUND((IDX_F2-MIN_IDX_F2)/(MAX_IDX_F2-MIN_IDX_F2)*100,5) AS NORM_IDX_F2,
    ROUND((IDX_I1-MIN_IDX_I1)/(MAX_IDX_I1-MIN_IDX_I1)*100,5) AS NORM_IDX_I1,
    ROUND((CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT
FROM
    SULIM_PRDCT_MART_003 A,
    VW_MIN_MAX B
WHERE 1=1
AND SALE_YYMM <> '201907'
;

WITH VW_MIN_MAX AS (
SELECT  
    MAX(IDX_H1) AS MAX_IDX_H1,
    MIN(IDX_H1) AS MIN_IDX_H1,
    MAX(IDX_H2) AS MAX_IDX_H2,
    MIN(IDX_H2) AS MIN_IDX_H2,
    MAX(IDX_E3) AS MAX_IDX_E3,
    MIN(IDX_E3) AS MIN_IDX_E3,
    MAX(PORD_CNT)    AS MAX_CNT,
    MIN(PORD_CNT)    AS MIN_CNT
FROM SULIM_PRDCT_MART_TP1
)
SELECT
    SALE_YYMM,
    PORD_CNT AS CNT,
    ROUND((IDX_H1-MIN_IDX_H1)/(MAX_IDX_H1-MIN_IDX_H1)*100,5) AS NORM_IDX_H1,
    ROUND((IDX_H2-MIN_IDX_H2)/(MAX_IDX_H2-MIN_IDX_H2)*100,5) AS NORM_IDX_H2,
    ROUND((IDX_E3-MIN_IDX_E3)/(MAX_IDX_E3-MIN_IDX_E3)*100,5) AS NORM_IDX_E3,
    ROUND((PORD_CNT-MIN_CNT)/(MAX_CNT-MIN_CNT)*100,5) AS NORM_CNT
FROM
    SULIM_PRDCT_MART_TP1 A,
    VW_MIN_MAX B
WHERE 1=1
AND SALE_YYMM <> '201907'
;

SELECT * FROM SULIM_PRDCT_MART_001 ORDER BY 1 DESC;

SELECT DISTINCT PRDG_CD, PRDG_NM FROM WJM.TD_PD_PROD;