SELECT
    H1.SALE_YYMM,
    H1.PORD_CNT_M1  AS IDX_H1,
    H2.PORD_CNT_M3  AS IDX_H2,
    E3.PRDCT_CNT    AS IDX_E3,
    H1.PORD_CNT
    
FROM
    SULIM_PRDT_IDX_H_1 H1,
    SULIM_PRDT_IDX_E_3 E3,
    SULIM_PRDT_IDX_H_2 H2
WHERE 1=1
AND H1.SALE_YYMM = E3.SALE_YYMM
AND H1.SALE_YYMM = H2.SALE_YYMM

ORDER BY
    SALE_YYMM