
-- 1. 순주문/총주문
CREATE TABLE SULIM_ORD_CNT AS 
WITH VW_ORD_CNT AS (
SELECT SALE_YYMM
      ,SLPART_CD
      ,PRDG_CD
      ,SUM(DECODE(PORD_YN,'X',1,0)) PORD_CNT
      ,SUM(DECODE(TORD_YN,'X',1,0)) TORD_CNT
  FROM WJM.TW_CT_SALE_MST_MM
 WHERE 1=1
   AND TOVR_SALE_YN <> 'X'
 GROUP BY 
       SALE_YYMM
      ,SLPART_CD
      ,PRDG_CD
)
, VW_PRDG AS (
SELECT DISTINCT PRDG_CD, PRDG_NM
  FROM WJM.TD_PD_PROD
)
SELECT A.SALE_YYMM
      ,A.SLPART_CD
      ,B.SLPART_NM
      ,A.PRDG_CD
      ,C.PRDG_NM
      ,A.PORD_CNT
      ,A.TORD_CNT
  FROM VW_ORD_CNT A
      ,WJM.TD_CT_SLPART B
      ,VW_PRDG C
 WHERE A.SLPART_CD = B.SLPART_CD(+)
   AND A.PRDG_CD = C.PRDG_CD
;

-- 2. 해약
CREATE TABLE SULIM_CNCL_CNT AS
SELECT /*+ PARALLEL(8) FULL(A B C) */
       A.PROD_YM AS CNCL_YYMM
      ,B.SLPART_CD
      ,B.SLPART_NM
      ,C.PRDG_CD
      ,C.PRDG_NM
      ,COUNT(1) CNCL_CNT
  FROM WJO.TO_ZBWT1003 A
      ,WJM.TD_CT_SLPART B
      ,WJM.TD_PD_PROD C
 WHERE A.PROD_DAY = TO_CHAR(ADD_MONTHS(TO_DATE(A.PROD_YM,'YYYYMM'),1)-1,'DD')
   AND A.RTN_CONF_DT BETWEEN '19900101' AND '99991231'
   AND A.CONTRACT_ID   = '2'
   AND A.VALUATION_CK1 = 'X'
   AND A.CONTRACT_ID = B.SLPART_CD(+)
   AND A.GOODS_CD = C.PROD_CD(+)
 GROUP BY 
       A.PROD_YM
      ,B.SLPART_CD
      ,B.SLPART_NM
      ,C.PRDG_CD
      ,C.PRDG_NM
;

-- 3. 소유권도래
CREATE TABLE SULIM_OWNE_CNT AS
SELECT /*+ PARALLEL(8) FULL(A B) */ 
       A.YYYY_MM AS OWNE_YYMM
      ,'2' AS SLPART_CD
      ,'렌탈' AS SLPART_NM
      ,B.PRDG_CD
      ,B.PRDG_NM
      ,COUNT(1) OWNE_CNT 
  FROM TO_ZSDT1048 A
      ,WJM.TD_PD_PROD B 
 WHERE A.YYYY_MM = A.FIRST_YM
   AND A.GOODS_CD = B.PROD_CD
 GROUP BY 
       A.YYYY_MM
      ,B.PRDG_CD
      ,B.PRDG_NM
;

-- 4. 영업조직원수
DROP TABLE SULIM_ORGM_CNT;

CREATE TABLE SULIM_ORGM_CNT AS 
SELECT /*+ PARALLEL(4)*/
SUBSTR(A.PROD_YMD,1,6) SALE_YYMM,
A.CONTRACT_ID SLPART_CD,
COUNT(DISTINCT A.SALE_ORG_CD) ORG_CNT,
COUNT(DISTINCT A.SALE_UEMPL_NO) EMP_CNT

FROM WJO.TO_ZBWT0100 A
WHERE A.PROD_YMD = TO_CHAR(ADD_MONTHS(TO_DATE(SUBSTR(PROD_YMD,1,6),'YYYYMM'),1)-1,'YYYYMMDD')
GROUP BY
SUBSTR(A.PROD_YMD,1,6),
A.CONTRACT_ID;

SELECT * FROM WJO.TO_ZBWT0100 A;

-- 5. 월별판매제품수
CREATE TABLE SULIM_PROD_CNT AS
WITH VW_PROD AS (
SELECT /*+ PARALLEL(4) */
       DISTINCT 
       SALE_YYMM,
       PRDG_CD,
       PRDG_NM,
       PROD_CD
  FROM WJM.TW_CT_SALE_MST_MM
 WHERE 1=1
   AND SALE_YYMM <> '100001'
   AND TOVR_SALE_YN <> 'X'
)
, VW_NEW_PROD AS (
SELECT SALE_YYMM,
       PRDG_CD,
       COUNT(1) NEW_PROD_CNT
  FROM VW_PROD A
 WHERE 1=1
   AND NOT EXISTS (SELECT 'X' FROM VW_PROD X WHERE X.SALE_YYMM < A.SALE_YYMM AND X.PROD_CD = A.PROD_CD)
 GROUP BY
       SALE_YYMM,
       PRDG_CD
)
SELECT A.*,
       NVL(B.NEW_PROD_CNT,0) AS NEW_PROD_CNT
  FROM (SELECT SALE_YYMM,
               PRDG_CD,
               PRDG_NM,
               COUNT(1) SALE_PROD_CNT
          FROM VW_PROD
         GROUP BY 
               SALE_YYMM,
               PRDG_CD,
               PRDG_NM ) A
      , VW_NEW_PROD B
 WHERE A.SALE_YYMM = B.SALE_YYMM(+)
   AND A.PRDG_CD = B.PRDG_CD(+)
 ORDER BY 1,2;

-- 6. 월별 서비스수
CREATE TABLE SULIM_SVC_CNT AS 
SELECT /*+ PARALLEL(8) */
    A.STD_YM,
    C.PRDG_CD,
    C.PRDG_NM,
    B.PROC_TYP,
    B.PROC_TYP_NM,
    COUNT(1) SVC_CNT
FROM 
    WJM.TM_SRVC_ASVC_M1 A,
    WJM.TM_CD_PROC_TYP B,
    WJM.TD_PD_PROD C
WHERE 1=1
AND A.PROC_TYP = B.PROC_TYP
AND A.GOODS_CD = C.PROD_CD
GROUP BY
    A.STD_YM,
    C.PRDG_CD,
    C.PRDG_NM,
    B.PROC_TYP,
    B.PROC_TYP_NM;

CREATE TABLE SULIM_RECV_CNT AS     
SELECT /*+ PARALLEL(8) */
    SUBSTR(RECV_DT,1,6) AS RECV_YYMM,
    COUNT(1) AS RECV_CNT
FROM
    WJO.TO_ZCST1022
GROUP BY 
    SUBSTR(RECV_DT,1,6)
;


