WITH VW_GR AS (
SELECT
    A.*,
    DECODE(B.PORD_CNT,0,0,ROUND(A.PORD_CNT/B.PORD_CNT,5)) AS GR,
    TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') AS M1,
    TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') AS M2,
    TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-3),'YYYYMM') AS M3
FROM
    SULIM_ORD_CNT A,
    SULIM_ORD_CNT B
WHERE 1=1
AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM
AND A.SLPART_CD = B.SLPART_CD
AND A.PRDG_CD = B.PRDG_CD
)
, VW_GR_PORD_CNT AS (
SELECT A.*
      ,ROUND((NVL(B1.GR,1)+NVL(B2.GR,1)+NVL(B3.GR,1))/3,5) RCNT_6_AVG_GR
      ,ROUND(B1.PORD_CNT*((NVL(B1.GR,1)+NVL(B2.GR,1))/3),0) GR_PORD_CNT
  FROM
    VW_GR A,
    VW_GR B1,
    VW_GR B2,
    VW_GR B3
WHERE 1=1
AND A.M1 = B1.SALE_YYMM(+) AND A.SLPART_CD = B1.SLPART_CD(+) AND A.PRDG_CD = B1.PRDG_CD(+)
AND A.M2 = B2.SALE_YYMM(+) AND A.SLPART_CD = B2.SLPART_CD(+) AND A.PRDG_CD = B2.PRDG_CD(+)
AND A.M3 = B3.SALE_YYMM(+) AND A.SLPART_CD = B3.SLPART_CD(+) AND A.PRDG_CD = B3.PRDG_CD(+)
AND B1.PORD_CNT IS NOT NULL
)
SELECT 
    A.SALE_YYMM,
    A.SLPART_CD,
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510,

    SUM(DECODE(A.PRDG_CD,'001',A.GR_PORD_CNT,0)) GR_PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.GR_PORD_CNT,0)) GR_PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.GR_PORD_CNT,0)) GR_PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.GR_PORD_CNT,0)) GR_PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.GR_PORD_CNT,0)) GR_PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.GR_PORD_CNT,0)) GR_PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.GR_PORD_CNT,0)) GR_PORD_CNT_510
FROM 
    VW_GR_PORD_CNT A
WHERE 1=1
AND A.SLPART_CD = '2'
GROUP BY
    SALE_YYMM,
    SLPART_CD
ORDER BY
    SALE_YYMM,
    SLPART_CD
;


SELECT 
    A.SALE_YYMM,
    
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510,
    
    SUM(DECODE(A.PRDG_CD,'001',B.CNCL_CNT,0)) CNCL_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',B.CNCL_CNT,0)) CNCL_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',B.CNCL_CNT,0)) CNCL_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',B.CNCL_CNT,0)) CNCL_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',B.CNCL_CNT,0)) CNCL_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',B.CNCL_CNT,0)) CNCL_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',B.CNCL_CNT,0)) CNCL_CNT_510
    
  FROM SULIM_ORD_CNT A
      ,SULIM_CNCL_CNT B
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.CNCL_YYMM
   AND A.PRDG_CD = B.PRDG_CD
   AND A.SLPART_CD = B.SLPART_CD
   AND A.SLPART_CD = '2'
GROUP BY
    A.SALE_YYMM
ORDER BY
    A.SALE_YYMM;

    
SELECT
--    A.*,
--    DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)) CNCL_PCNT
      
    A.SALE_YYMM,
    
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510,
    
    SUM(DECODE(A.PRDG_CD,'001',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_001,
    SUM(DECODE(A.PRDG_CD,'002',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_002,
    SUM(DECODE(A.PRDG_CD,'003',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_003,
    SUM(DECODE(A.PRDG_CD,'004',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_004,
    SUM(DECODE(A.PRDG_CD,'007',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_007,
    SUM(DECODE(A.PRDG_CD,'008',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_008,
    SUM(DECODE(A.PRDG_CD,'510',DECODE(C.PORD_CNT,0,0,ROUND(B.CNCL_CNT/C.PORD_CNT,5)),0)) CNCL_PCNT_510
      
  FROM SULIM_ORD_CNT A
      ,SULIM_CNCL_CNT B
      ,SULIM_ORD_CNT C
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.CNCL_YYMM
   AND A.PRDG_CD = B.PRDG_CD
   AND A.SLPART_CD = B.SLPART_CD
   AND B.CNCL_YYMM = C.SALE_YYMM
   AND B.PRDG_CD = C.PRDG_CD
   AND B.SLPART_CD = C.SLPART_CD
   AND A.SLPART_CD = '2'
GROUP BY
    A.SALE_YYMM
ORDER BY
    A.SALE_YYMM;

WITH VW_SVC AS (
SELECT
    STD_YM,
    SUM(DECODE(PROC_TYP,'1',SVC_CNT,0)) PROC_TYP_1,
    SUM(DECODE(PROC_TYP,'2',SVC_CNT,0)) PROC_TYP_2,
    SUM(DECODE(PROC_TYP,'3',SVC_CNT,0)) PROC_TYP_3,
    SUM(DECODE(PROC_TYP,'4',SVC_CNT,0)) PROC_TYP_4,
    SUM(DECODE(PROC_TYP,'5',SVC_CNT,0)) PROC_TYP_5,
    SUM(DECODE(PROC_TYP,'6',SVC_CNT,0)) PROC_TYP_6
FROM 
    SULIM_SVC_CNT
WHERE 1=1
GROUP BY
    STD_YM
)
, VW_ORD_CNT AS (
SELECT
    A.SALE_YYMM,
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510
FROM 
    SULIM_ORD_CNT A
WHERE 1=1
AND A.SLPART_CD = '2'
GROUP BY
    A.SALE_YYMM
)
SELECT *
FROM
    VW_ORD_CNT A,
    VW_SVC B
WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.STD_YM
ORDER BY
    1
;

WITH VW_ORD_CNT AS (
SELECT
    A.SALE_YYMM,
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510
FROM 
    SULIM_ORD_CNT A
WHERE 1=1
AND A.SLPART_CD = '2'
GROUP BY
    A.SALE_YYMM
)
SELECT *
FROM
    VW_ORD_CNT A,
    SULIM_RECV_CNT B
WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.RECV_YYMM
ORDER BY
    1;
    
WITH VW_CNCL_PCNT AS (
SELECT A.*,
       DECODE(C.PORD_CNT,0,0,B.CNCL_CNT/C.PORD_CNT) CNCL_PCNT
  FROM SULIM_ORD_CNT A
      ,SULIM_CNCL_CNT B
      ,SULIM_ORD_CNT C
 WHERE TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.CNCL_YYMM
   AND A.PRDG_CD = B.PRDG_CD
   AND A.SLPART_CD = B.SLPART_CD
   AND B.CNCL_YYMM = C.SALE_YYMM
   AND B.PRDG_CD = C.PRDG_CD
   AND B.SLPART_CD = C.SLPART_CD
)
, VW_SRC AS (
SELECT 
    A.SALE_YYMM,
    A.SLPART_CD,
    A.SLPART_NM,
    A.PRDG_CD,
    A.PRDG_NM,
    A.PORD_CNT,
    ROUND((A.CNCL_PCNT+B.CNCL_PCNT+C.CNCL_PCNT)/3,5) AS AVG_CNCL_PCNT

  FROM VW_CNCL_PCNT A
      ,VW_CNCL_PCNT B
      ,VW_CNCL_PCNT C
 WHERE 1=1
   AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B.SALE_YYMM
   AND A.PRDG_CD = B.PRDG_CD
   AND A.SLPART_CD = B.SLPART_CD
   AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') = C.SALE_YYMM
   AND B.PRDG_CD = C.PRDG_CD
   AND B.SLPART_CD = C.SLPART_CD
   AND A.SLPART_CD = '2'
)
SELECT
    A.SALE_YYMM,

    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510,
    
    SUM(DECODE(A.PRDG_CD,'001',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.AVG_CNCL_PCNT,0)) AVG_CNCL_PCNT_510
FROM
    VW_SRC A
GROUP BY
    SALE_YYMM
ORDER BY
    SALE_YYMM;
    
SELECT 
    A.*,
    B.SALE_PROD_CNT,
    B.NEW_PROD_CNT
FROM 
    SULIM_ORD_CNT A,
    SULIM_PROD_CNT B
WHERE 1=1
AND A.SALE_YYMM = B.SALE_YYMM
AND A.PRDG_CD = B.PRDG_CD
AND A.SLPART_CD = '2'
 ORDER BY 1,2,4
;

WITH VW_SRC AS (
SELECT 
    A.*,
    B.SALE_PROD_CNT,
    B.NEW_PROD_CNT
FROM
    SULIM_ORD_CNT A,
    SULIM_PROD_CNT B
WHERE A.SALE_YYMM = B.SALE_YYMM
AND A.SLPART_CD = '2'
AND A.PRDG_CD = B.PRDG_CD
)
, VW_STTS AS (
SELECT
    A.*,
    B1.SALE_PROD_CNT+B2.SALE_PROD_CNT+B3.SALE_PROD_CNT AS SUM_SALE_PROD_CNT,
    B1.NEW_PROD_CNT+B2.NEW_PROD_CNT+B3.NEW_PROD_CNT AS SUM_NEW_PROD_CNT,
--    B.SALE_PROD_CNT,
--    B.NEW_PROD_CNT,
     ROUND((A.PORD_CNT-B1.PORD_CNT+B1.PORD_CNT-B2.PORD_CNT+B2.PORD_CNT-B3.PORD_CNT)
          /(B1.SALE_PROD_CNT+B2.SALE_PROD_CNT+B3.SALE_PROD_CNT)*(B1.NEW_PROD_CNT+B2.NEW_PROD_CNT+B3.NEW_PROD_CNT)) IDX_NEW_PROD_CNTR
FROM
    VW_SRC A,
    VW_SRC B1,
    VW_SRC B2,
    VW_SRC B3
WHERE 1=1
AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-1),'YYYYMM') = B1.SALE_YYMM
AND A.SLPART_CD = B1.SLPART_CD
AND A.PRDG_CD = B1.PRDG_CD
AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-2),'YYYYMM') = B2.SALE_YYMM
AND A.SLPART_CD = B2.SLPART_CD
AND A.PRDG_CD = B2.PRDG_CD
AND TO_CHAR(ADD_MONTHS(TO_DATE(A.SALE_YYMM,'YYYYMM'),-3),'YYYYMM') = B3.SALE_YYMM
AND A.SLPART_CD = B3.SLPART_CD
AND A.PRDG_CD = B3.PRDG_CD
)
SELECT
    A.SALE_YYMM,
    
    SUM(DECODE(A.PRDG_CD,'001',A.PORD_CNT,0)) PORD_CNT_001,
    SUM(DECODE(A.PRDG_CD,'002',A.PORD_CNT,0)) PORD_CNT_002,
    SUM(DECODE(A.PRDG_CD,'003',A.PORD_CNT,0)) PORD_CNT_003,
    SUM(DECODE(A.PRDG_CD,'004',A.PORD_CNT,0)) PORD_CNT_004,
    SUM(DECODE(A.PRDG_CD,'007',A.PORD_CNT,0)) PORD_CNT_007,
    SUM(DECODE(A.PRDG_CD,'008',A.PORD_CNT,0)) PORD_CNT_008,
    SUM(DECODE(A.PRDG_CD,'510',A.PORD_CNT,0)) PORD_CNT_510,
    
    SUM(DECODE(A.PRDG_CD,'001',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_001,
    SUM(DECODE(A.PRDG_CD,'002',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_002,
    SUM(DECODE(A.PRDG_CD,'003',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_003,
    SUM(DECODE(A.PRDG_CD,'004',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_004,
    SUM(DECODE(A.PRDG_CD,'007',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_007,
    SUM(DECODE(A.PRDG_CD,'008',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_008,
    SUM(DECODE(A.PRDG_CD,'510',A.IDX_NEW_PROD_CNTR,0)) IDX_NEW_PROD_CNTR_510
FROM
    VW_STTS A
GROUP BY
    A.SALE_YYMM
ORDER BY 
    A.SALE_YYMM